### ISSUE TITLE
语音文件太大国内下不来

### ISSUE THREAD

**Issue by caiweilv** [dominoar/QChatPlugins#1]
老是传到一半就跳验证窗口

**Comment by dominoar** [comment]
请尝试更换代理，或者等待支持gitee


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dominoar/QChatPlugins"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月1日(星期三) 晚上11:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dominoar/QChatPlugins] 语音文件太大国内下不来 (Issue #1)





 
老是传到一半就跳验证窗口
