### ISSUE TITLE
提示语音silk生成成功！ヽ(￣▽￣)ﾉ没反应后

### ISSUE THREAD

**Issue by sizxiwu** [dominoar/QChatPlugins#5]
![屏幕截图(47)](https://user-images.githubusercontent.com/121373708/217589945-64ee1661-06a9-41ca-83a0-8587db1f0705.png)

**Comment by sizxiwu** [comment]
![屏幕截图(48)](https://user-images.githubusercontent.com/121373708/217590106-5bf51399-ae14-4f60-be1b-accfb5651d8d.png)

**Comment by Akinpzx** [comment]
请问你是如何解决这个问题的呢，我也是生成之后就没反应了
