### ISSUE TITLE
生成了silk文件之后 插件ChatWaifu触发事件normal_message_responded时发生错误 显示目标计算机积极拒绝

### ISSUE THREAD

**Issue by Akinpzx** [dominoar/QChatPlugins#7]
显示目标计算机积极拒绝，无法连接，请问如何解决？
![image](https://user-images.githubusercontent.com/95456509/218109255-c52ceee0-3052-408d-9fd8-274da64d2231.png)

**Comment by TonokoTakatsuki** [comment]
我将ChatWaifu中的config.py中的gocq_voice = True改成了False就好了。另外这个只能群聊发送，不能私聊。
